In [ ]:
""" Creating dataframe """
1 - pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=(1,2,3),columns=(1,2,3))
2 - pd.read_csv()
3 - pd.read_clipboard() # reading data frame you copied
4 - pd.DataFrame({'a':[1,2],'b':[3,4]})

""" attributes """
1 - a.index   # showing row names
2 - a.columns # showing columns names

""" function """
1 - a.head()  # showing first n rows n=5 default
2 - a.tail()  # showing last n rows n=5 default
3 - a.reindex(index_list,fill_value=NAN,method='ffill',columns='')#  index_list is list of index method='ffill' example above
                        # fill_value to fill all missing valuse  columns if showed it will reindex coulumns instead of rows
4 - a.drop('str',axis=0) # if axis ==0 drop row if axis=1 drop column all with name str
5 - a.dropna(how='all')  # drop all nan values the parameter [how='any',thresh=2] second is maximum to drop 
6 - a.fillna(0)     #replacing all nan values with 0 mighit take dictionary but every index refer to the column
7 - a.add(b,fill_value=0) # like a+b  but the valuse than dosen't exists in one of them will be 0 
8 - a.sort_index()  # sorting with index
9 - a.idxmin() # find the minimum valuse in dateframe but return their index instead of the values
10 - a.cumsum()# get the sum of colum and update the colum after it then get it's sum ans so on
11 - a.describe() # get info about the date frame
12 - a.unstack() # converting series of 2d index to dataframe
13 - a.merge() # megrging two dataframes look for more information
14 - a.concat([df1,df2],axis=0,ignore_index=0) # to concatenate two dataframes
15 - a.combine_first(b)  # concat two dataframes get value of b when a is null
16 - a.duplicated()    or a.drop_duplicates(['columns_name '],take_last=0) # both are optional
17 - a.replace([key,value],[key2,value2]) # replacing every number with other
18 - a['col'].map(dictionary) take the dic and replace each key in the a['col'] with it's value in dictionary
19 - a.rename(index=0,column=0)
20 - a.pivot_table(index=['a']) # to group by a where a is some column


""" Few techniques """
1 - df[np.abs(df)>3] = pd.sign(df)*3






""" accessing  """
1 - a[['1','2']]   # getting column 1 and 2 
2 - a.loc['a']       # getting index by name
3 - a.iloc[0]     # getting index by place 0 is always the first
4 - a['new'] = pd.Series(['5','2'],index=(3,2)) # creating or changing columns 'new' to [NAN,NAN,2,5,NAN,NAN,....,NAN]
5 - del a['new'] # deleting column













In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
df = pd.read_csv("data/train.csv")

In [3]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [10]:
df.Pclass.value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [9]:
df.groupby('Pclass').mean()

PassengerId  Survived        Age     SibSp     Parch       Fare
Pclass                                                                 
1        461.597222  0.629630  38.233441  0.416667  0.356481  84.154687
2        445.956522  0.472826  29.877630  0.402174  0.380435  20.662183
3        439.154786  0.242363  25.140620  0.615071  0.393075  13.675550

In [2]:
df = pd.DataFrame({
    'one':[1,2,3,4,5],
    "two":[5,2,np.nan,3,2],
    "three":[512,51,512,np.nan,2],
})

In [82]:
df.head()

one  two  three
0    1  5.0  512.0
1    2  2.0   51.0
2    3  NaN  512.0
3    4  3.0    NaN
4    5  2.0    2.0

In [4]:
def fill_null_with_mostcommon(df):
    for i in df.columns:
        df[i].fillna(df[i].mode()[0],inplace=True)

In [88]:
fill_null_with_mostcommon(df)

In [85]:
df2.head()

one  two  three
0    1  5.0  512.0
1    2  2.0   51.0
2    3  2.0  512.0
3    4  3.0  512.0
4    5  2.0    2.0

In [89]:
df

one  two  three
0    1  5.0  512.0
1    2  2.0   51.0
2    3  2.0  512.0
3    4  3.0  512.0
4    5  2.0    2.0

In [90]:
m = {1:10,2:20,3:30,4:40,5:50}

In [91]:
df['one'].map(m)

0    10
1    20
2    30
3    40
4    50
Name: one, dtype: int64

In [94]:
df['one'] =  df['one'].map(m)

In [3]:
df

one  two  three
0    1  5.0  512.0
1    2  2.0   51.0
2    3  NaN  512.0
3    4  3.0    NaN
4    5  2.0    2.0

In [5]:
fill_null_with_mostcommon(df)

In [6]:
df

one  two  three
0    1  5.0  512.0
1    2  2.0   51.0
2    3  2.0  512.0
3    4  3.0  512.0
4    5  2.0    2.0

In [7]:
from sklearn.preprocessing import *

In [12]:
hot = OneHotEncoder()

In [32]:
hot.fit(np.array(df['two']).reshape(-1,1))

OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [36]:
k = hot.transform(np.array(df['one']).reshape(-1,1))

ValueError: Found unknown categories [1, 4] in column 0 during transform

In [34]:
hot.categories_

[array([2., 3., 5.])]

In [35]:
k.toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [37]:
arr = np.array([2,2,2,3,3])

In [39]:
k2 = hot.transform(arr.reshape(-1,1))

In [40]:
k2.toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [71]:
df2 = pd.DataFrame(k.toarray(),columns=np.array(hot.categories_).flatten())

In [72]:
df2

2.0  3.0  5.0
0  0.0  0.0  1.0
1  1.0  0.0  0.0
2  1.0  0.0  0.0
3  0.0  1.0  0.0
4  1.0  0.0  0.0

In [73]:
pd.concat([df,df2],axis=1)

one  two  three  2.0  3.0  5.0
0    1  5.0  512.0  0.0  0.0  1.0
1    2  2.0   51.0  1.0  0.0  0.0
2    3  2.0  512.0  1.0  0.0  0.0
3    4  3.0  512.0  0.0  1.0  0.0
4    5  2.0    2.0  1.0  0.0  0.0

[2, 3, 5]

array([2., 3., 5.])